### PR TITLE
Added support of Laravel 8 + Added PSR-4 compliance

### PR DESCRIPTION
**Pull request by xUJYx**
Added support of laravel 8
Fixed errors with PSR 4 autoloading standards

### CODE REVIEW

**Review by Anas-shamia — APPROVED** [review]
Thank you for your contribution, and wait for our surprises and a lot of new amazing packages

**Comment by didix16** [comment]
Any plan when the changes will be merged?

**Comment by Kaylakaze** [comment]
Never. DigitalCloud seems to be dead.

**Comment by xUJYx** [comment]
> Never. DigitalCloud seems to be dead.

But @Anas-shamia left comment, maybe he could make merge...

**Review by muhammadsaeedparacha — APPROVED** [review]

**Comment by ghost** [comment]
Anything new here? Would really appreciate a Merge

**Comment by xUJYx** [comment]
@devmtm could you please make merge of this pull request?

**Comment by sfinktah** [comment]
Good work @xUJYx I'm growing tired of waiting, so I'm going to merge these PR's into a fork and put it on composer.

*shrug* better than nothing 📦 

```bash
composer require prima-ca/nova-custom-views
```

**Review by bsaqqa — APPROVED** [review]

**Comment by bsaqqa** [comment]
Thanks for your PR 
@xUJYx 

Thanks @sfinktah

**Pull request merged**
